<b>MyPHPpa</b><br>
<div id='index_txt'>
Copyright (C) 2003, 2007, 2016 Jens Beyer<br>

<div id='gpl'>
<br>
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.<br>

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.<br>

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
</div></div>
<br>
This is a webrowser (text!) based multi user ticker driven science fiction space game.<br>
Download code at <a href="https://github.com/jaypeeteeB/MyPHPpa">GitHub</a> 
or visit <a href="http://myphppa.de">MyPHPpa Homepage</a>.
<br>
<br>
This site uses cookies to enhance the game experience. By login in
or signing in you accept this.
